---
deployment:
  tasks:
    - /bin/cp -rf index.html style.css .htaccess /home/seanw2/public_html/votewood.ca/
    - /bin/cp -rf prepared/ /home/seanw2/public_html/votewood.ca/
    - /bin/cp -rf cron/ /home/seanw2/public_html/votewood.ca/
    - /bin/cp -rf water/ /home/seanw2/public_html/votewood.ca/
    - /bin/cp -rf housing/ /home/seanw2/public_html/votewood.ca/
    - /bin/cp -rf downtown/ /home/seanw2/public_html/votewood.ca/
    - /bin/cp -rf parks/ /home/seanw2/public_html/votewood.ca/
    - /bin/cp -rf safety/ /home/seanw2/public_html/votewood.ca/
    - /bin/cp -rf community/ /home/seanw2/public_html/votewood.ca/
    - /bin/cp -rf environment/ /home/seanw2/public_html/votewood.ca/
    - /bin/cp -rf infrastructure/ /home/seanw2/public_html/votewood.ca/
    - /bin/cp -rf grants/ /home/seanw2/public_html/votewood.ca/
